function examToggleSearchBox(){$("#searchExam").toggle()}function examSearchExamList(){var a={exam_name:$.trim($("#exam_name").val())},b=$('table[_pagetabledataset="exam::getExamPageTable"]');window.L.extension.pageTable.classObj.params(b.get(0),a,!0)}function examSearchExerciseList(){var a={exam_name:$.trim($("#exam_name").val())},b=$('table[_pagetabledataset="exam_examCtl::getExercisePageTable"]');window.L.extension.pageTable.classObj.params(b.get(0),a,!0)}
function examInitExamList(){var a="",b=null,c=null,e=null,g="0",h='<span class="ddf-btn ddf-btn_enter disabled">'+window.L.getText("\u5ba1\u6838\u672a\u901a\u8fc7")+"</span>",i='<span class="ddf-btn ddf-btn_enter">'+window.L.getText("\u5ba1\u6838\u5df2\u901a\u8fc7")+"</span>",j='<span class="ddf-btn ddf-btn_enter disabled">'+window.L.getText("\u5df2\u7533\u8bf7\u5f85\u5ba1\u6838")+"</span>";$("input[name='exam_list_id']").each(function(){a=$(this).val();$("#exam_user_verify_flg_"+a).val();is_user_in_range=
!1;var k='<a href="#" class ="ddf-btn ddf-btn_enter" onclick="examDisplayUserSignUp(\''+a+"'); return false;\">"+window.L.getText("\u70b9\u51fb\u7533\u8bf7\u62a5\u540d")+"</a>";""!=$("#include_user_ids_"+a).val()&&(c=$("#include_user_ids_"+a).val().split(","),$.each(c,function(a,b){if(b==USER_ID)return is_user_in_range=!0,!1}));e=L.json($("#include_group_json_"+a).val());void 0!=e?$.each(USER_GROUP,function(a,b){$.each(e,function(e,c){if(a=="0"&&b==c.group_id||a!="0"&&b==c.group_id&&c.is_include_sub==
"1"){is_user_in_range=true;return false}})}):is_user_in_range=!0;b=$("#exclude_user_ids_"+a).val().split(",");$.each(b,function(a,b){if(b==USER_ID)return is_user_in_range=false});g=$("#exam_user_signup_flg_"+a).val();var l=$("#sign_up_end_time_"+a).val(),f=$("#time_"+a).val(),m=$("#beginTime_"+a).val(),n=$("#endTime_"+a).val(),d=$("#exam_user_verify_"+a).val();is_user_in_range=n<f?!1:!0;if("1"==g){if(l<=f&&""==d)return $("#exam_btn_"+a).html('<span class="ddf-btn ddf-btn_enter disabled">'+L.getText("\u62a5\u540d\u5df2\u7ed3\u675f")+
"</span>"),!1;d=$("#exam_user_verify_"+a).val();""==d?$("#exam_btn_"+a).html(k):"070202"==d?$("#exam_btn_"+a).html(h):"070203"==d?$("#exam_btn_"+a).html(j):f<m&&$("#exam_btn_"+a).html(i)}})}
function examDisplayUserSignUp(a){window.L.open("oDialogDiv");oDialogDiv(L.getText("\u7533\u8bf7\u62a5\u540d"),'text:<div class="q-applybox" style="width:400px; height:50px;"><div class="q-popupTitle">'+window.L.getText("\u7533\u8bf7\u4fe1\u606f")+'</div><textarea class="q-popupTextarea" id="app_content" name="app_content"></textarea></div>',"auto","auto",[2,function(b){if(b){var b=ROOT_URL+"/exam/examCtl.php?a=userVerify",c="exam_id="+a+"&app_content="+$("#app_content").val();$.ajax({type:"POST",
async:!1,url:b,data:c,dataType:"json",success:function(a){"success"==a.res?(a=void 0==$('table[_pagetabledataset="exam::getExamPageTable"]').get(0)?$('table[_pagetabledataset="exam_exerciseCtl::getExercisePageTable"]'):$('table[_pagetabledataset="exam::getExamPageTable"]'),window.L.extension.pageTable.classObj.pageClickFn(a.get(0),0)(),window.L.open("oDialogDiv")(window.L.getText("\u7533\u8bf7\u4fe1\u606f"),'<div class="q-popupCon">'+window.L.getText("\u7533\u8bf7\u5df2\u63d0\u4ea4\uff0c\u8bf7\u7b49\u5f85\u5ba1\u6838\u3002")+
"</div>","240px","150px",[1])):oDialogDivInfo(a.info)},error:function(){}})}}])}
function examIsIeOnly(a){if(a){if(-1!=navigator.appName.indexOf("Microsoft")){try{ie.IsOk()}catch(b){return window.L.open("oDialogDiv"),oDialogDiv(window.L.getText("\u6d88\u606f"),"text:<div>"+window.L.getText("\u672a\u542f\u7528\u6216\u5b89\u88c5\u5168\u5c4f\u63d2\u4ef6,\u70b9\u51fb\u786e\u5b9a\u4e0b\u8f7d\u5168\u5c4f\u63d2\u4ef6")+"</div>","270px","150px",[2,function(a){a&&examDownLoadFullScreenPlugin();return!0}]),!1}return!0}window.L.open("oDialogDiv");oDialogDiv(window.L.getText("\u6d88\u606f"),
"text:<div>"+window.L.getText("\u672c\u6b21\u8003\u8bd5\u53ea\u80fd\u7528IE\u6d4f\u89c8\u5668\u6253\u5f00")+"</div>","270px","150px",[1,function(){}]);return!1}return!0}function examDownLoadFullScreenPlugin(){window.location.href=ROOT_URL+"/exam.php?a=downloadFullScreenPlugin"}
function examCategoryTreeShow(a,b,c){getTree({targetNameId:a,targetValueId:b,dataType:"exam_category",showRoot:c?c:!1,isFront:!0,callbackFn:function(){$("ul.ddf-subtitle li a").removeClass().addClass("ddf-subtitle_list");$("#exam_category_name").addClass("ddf-subtitle_list_h");var a=window.L.extension.pageTable.classObj,b=document.getElementById("getExamPageTable"),c=a.params(b);c.exam_category=$.trim($("#exam_category").val());a.params(b,c,!0)}})}
function examTreeShow(a,b,c){getTree({targetNameId:a,targetValueId:b,dataType:c,showRoot:!1,isFront:!0,callbackFn:function(){$("ul.ddf-subtitle li a").removeClass().addClass("ddf-subtitle_list");$("#exam_category_name").addClass("ddf-subtitle_list_h");var a=window.L.extension.pageTable.classObj,b=document.getElementById("getExamPageTable"),c=a.params(b);c.custom=$.trim($("#exam_category").val());a.params(b,c,!0)}})};
